### PR TITLE
Updates to haml-i18n-extractor

### PR DESCRIPTION
**Pull request by jeznag**
A bunch of improvements from several forks:
From mirasrael:
- support attribute i18nization
- support title tag attribute for TextFinder
- fix expression checking with ruby code

lovehandle:
- allow dir globbing
- improve key normalization process

peterwake:
- use lowercase keys

COzero:
- add ability to have nested locale config files
- fix tests broken by other contributions
- fix RSpec warnings

### CODE REVIEW

**Comment by shaiguitar** [comment]
The diff here is very large. Is this branch rebased/current? Topic branches would be nice to review the changes. I'm also have not been using this gem recently, if you'd like to participate in maintenance 👍

**Comment by jeznag** [comment]
Yeah I forked on top of the most advanced fork. Not really sure what the commits by other people do tbh :P 

I don't know what the best way to go forward is. Perhaps we can have a beta channel for this gem which includes these changes but the default version will remain at the current HEAD?

I'm happy to help with maintenance. My team has been using for a large i18n project and I've been fixing bugs as we go.

**Comment by shaiguitar** [comment]
Sure. Like mentioned, mine hasn't been used for a while now. If you'd like to link your forked repository, I could list it on this repos README to be a more active/updated version and let folks decide and check things out for themselves.

**Comment by jeznag** [comment]
That link is already in place :) https://github.com/COzero/haml-i18n-extractor

**Comment by shaiguitar** [comment]
Thanks @jeznag .

**Pull request closed without merging**
